language: java

env: LD_LIBRARY_PATH=/usr/lib/neko

before_install:
  # Install haxe
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  # Setup haxelib
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  # Download dependencies
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR
  - haxelib install lime > /dev/null
  - haxelib install openfl > /dev/null
  - haxelib install dox > /dev/null
  - ant tools
  - echo "y" | haxelib run HaxePunk setup

script:
  - ant clean build unit-travis

notifications:
  slack: openfl:sBwVO0kgB7EuWLYzZzUezVIz#haxepunk 
