language: haxe
haxe: "3.2.0-rc2"
neko: "2.0.0"

env: LD_LIBRARY_PATH=/usr/lib/neko

before_install:
  # Setup haxelib
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  # Download dependencies
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR
  - haxelib install lime > /dev/null
  - haxelib install openfl > /dev/null
  - haxelib install dox > /dev/null
  - ant tools
  - echo "y" | haxelib run HaxePunk setup

script:
  - ant clean build unit-travis

notifications:
  slack: openfl:sBwVO0kgB7EuWLYzZzUezVIz#haxepunk 
