language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  # Install haxe
  - sudo apt-get install haxe -y --force-yes
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  # Download dependencies
  - haxelib install format
  - haxelib install lime
  - echo "y" | haxelib run lime setup
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR

before_script:
  - cd $TRAVIS_BUILD_DIR/tests

script:
  - haxe test.hxml
