language: java

env: LD_LIBRARY_PATH=/usr/lib/neko

before_install:
  # Install neko 2.0
  - curl http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz | tar xzf -
  - sudo mv neko-2.0.0-linux /usr/lib/neko
  - sudo cp /usr/lib/neko/neko /usr/bin/neko
  - sudo cp /usr/lib/neko/nekoc /usr/bin/nekoc
  - sudo cp /usr/lib/neko/nekotools /usr/bin/nekotools
  # Install haxe 3.1 (thanks to openfl install script)
  - curl http://haxe.org/file/haxe-3.0.1-linux64.tar.gz | tar xzf -
  - sudo mv build /usr/lib/haxe
  - sudo ln -s /usr/lib/haxe/haxe /usr/bin/haxe
  - sudo ln -s /usr/lib/haxe/haxelib /usr/bin/haxelib
  # Setup haxelib
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  # Download dependencies
  - haxelib install openfl
  - haxelib install openfl-native
  - haxelib install openfl-html5-dom
  - haxelib install lime
  - haxelib install openfl-bitfive
  - echo "y" | haxelib run openfl setup
  # openfl command
  - sudo ln -s /usr/bin/lime /usr/bin/openfl

script:
  - ant clean build unit-travis
