language: haxe

haxe:
  - "3.2.0"
  - development

matrix:
  allow_failures:
    - haxe: development

neko: "2.0.0"

sudo: false

install:
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR
  - haxelib install lime > log.txt || cat log.txt
  - haxelib install openfl > log.txt || cat log.txt
  - haxelib install dox > log.txt || cat log.txt
  - haxelib list

before_script:
  - make tools
  - echo "y" | haxelib run HaxePunk setup

script:
  - make clean build unit-travis

cache:
  directories:
    - $HOME/haxe/lib

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - openfl:sBwVO0kgB7EuWLYzZzUezVIz#haxepunk
