language: haxe

haxe:
  - "3.2.0"
  - development

matrix:
  allow_failures:
    - haxe: development

env:
  - TARGET=flash COMMAND=openfl
  - TARGET=neko COMMAND=openfl
  - TARGET=cpp COMMAND=openfl
  - TARGET=html5 COMMAND=openfl
  - TARGET=flash COMMAND=nme
  - TARGET=neko COMMAND=nme
  - TARGET=cpp COMMAND=nme

neko: "2.0.0"

sudo: false

install:
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR
  - yes | haxelib install lime 2.9.1 > log.txt || cat log.txt
  - yes | haxelib install openfl 3.6.1 > log.txt || cat log.txt
  - yes | haxelib install dox > log.txt || cat log.txt
  - yes | haxelib install nme > log.txt || cat log.txt
  - haxelib list

before_script:
  - make tools
  - echo "n" | haxelib run HaxePunk setup

script:
  - make clean unit-travis examples COMMAND=$COMMAND TARGET=$TARGET

cache:
  directories:
    - $HOME/haxe/lib

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - openfl:sBwVO0kgB7EuWLYzZzUezVIz#haxepunk
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b5256a55779b5e854b0a
    on_success: change
    on_failure: always
    on_start: never
